[package]
name = "knn_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = "0.19.3"
wkt = "0.10.3"
geo = "0.24.0"
csv = "1.1"
rstar = "0.10.0"
