CREATE OR REPLACE FILE FORMAT GIS.PUBLIC.ORC_FORMAT
  TYPE = 'ORC';

-- code_point_open_white_horse.orc
CREATE OR REPLACE TABLE GIS.PUBLIC.CODE_POINT_OPEN_WHITE_HORSE
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(
      INFER_SCHEMA(
        LOCATION=>'@GIS.PUBLIC.KNN/code_point_open_white_horse.orc',
        FILE_FORMAT=>'GIS.PUBLIC.ORC_FORMAT'
      )
    )
  );

COPY INTO GIS.PUBLIC.CODE_POINT_OPEN_WHITE_HORSE
FROM @GIS.PUBLIC.KNN/code_point_open_white_horse.orc
PATTERN = '.*\.orc'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

CREATE OR REPLACE TABLE GIS.PUBLIC.CODE_POINT_OPEN_WHITE_HORSE
AS 
SELECT 
  *,
  ST_GEOMETRYFROMEWKB("geom_wkb", 27700) AS geom_wkb
FROM GIS.PUBLIC.CODE_POINT_OPEN_WHITE_HORSE;


-- Infer schema and create table for open_uprn_white_horse.orc
CREATE OR REPLACE TABLE GIS.PUBLIC.OPEN_UPRN_WHITE_HORSE
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(
      INFER_SCHEMA(
        LOCATION=>'@GIS.PUBLIC.KNN/open_uprn_white_horse.orc',
        FILE_FORMAT=>'GIS.PUBLIC.ORC_FORMAT'
      )
    )
  );

COPY INTO GIS.PUBLIC.OPEN_UPRN_WHITE_HORSE
FROM @GIS.PUBLIC.KNN/open_uprn_white_horse.orc
PATTERN = '.*\.orc'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

CREATE OR REPLACE TABLE GIS.PUBLIC.OPEN_UPRN_WHITE_HORSE
AS 
SELECT 
  *,
  ST_GEOMETRYFROMEWKB("geom_wkb", 27700) AS geom_wkb
FROM GIS.PUBLIC.OPEN_UPRN_WHITE_HORSE;

-- show
SELECT *
FROM GIS.PUBLIC.CODE_POINT_OPEN_WHITE_HORSE
LIMIT 10;
SELECT *
FROM GIS.PUBLIC.OPEN_UPRN_WHITE_HORSE
LIMIT 10;