CREATE OR REPLACE FILE FORMAT GIS.PUBLIC.ORC_FORMAT
  TYPE = 'ORC';

-- code_point_open_white_horse.orc
SELECT *
FROM TABLE(
  INFER_SCHEMA(
    LOCATION=>'@GIS.PUBLIC.KNN/code_point_open_white_horse.orc',
    FILE_FORMAT=>'GIS.PUBLIC.ORC_FORMAT'
  )
);

CREATE TABLE GIS.PUBLIC.CODE_POINT_OPEN_WHITE_HORSE
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(
      INFER_SCHEMA(
        LOCATION=>'@GIS.PUBLIC.KNN/code_point_open_white_horse.orc',
        FILE_FORMAT=>'GIS.PUBLIC.ORC_FORMAT'
      )
    )
  );

COPY INTO GIS.PUBLIC.CODE_POINT_OPEN_WHITE_HORSE
FROM @GIS.PUBLIC.KNN/code_point_open_white_horse.orc
PATTERN = '.*\.orc'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

-- Infer schema and create table for open_uprn_white_horse.orc
CREATE TABLE GIS.PUBLIC.OPEN_UPRN_WHITE_HORSE
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(
      INFER_SCHEMA(
        LOCATION=>'@GIS.PUBLIC.KNN/open_uprn_white_horse.orc',
        FILE_FORMAT=>'GIS.PUBLIC.ORC_FORMAT'
      )
    )
  );

COPY INTO GIS.PUBLIC.OPEN_UPRN_WHITE_HORSE
FROM @GIS.PUBLIC.KNN/open_uprn_white_horse.orc
PATTERN = '.*\.orc'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

-- For CODE_POINT_OPEN_WHITE_HORSE
ALTER TABLE GIS.PUBLIC.CODE_POINT_OPEN_WHITE_HORSE
ADD COLUMN geom_27700 GEOMETRY;

UPDATE GIS.PUBLIC.CODE_POINT_OPEN_WHITE_HORSE
SET geom_27700 = ST_GEOMETRYFROMEWKB(TO_BINARY('geom', 'HEX'), 27700);

-- For OPEN_UPRN_WHITE_HORSE
ALTER TABLE GIS.PUBLIC.OPEN_UPRN_WHITE_HORSE
ADD COLUMN geom_27700 GEOMETRY;

UPDATE GIS.PUBLIC.OPEN_UPRN_WHITE_HORSE
SET geom_27700 = ST_GEOMETRYFROMEWKB(TO_BINARY('geom', 'HEX'), 27700);

-- show
SELECT *
FROM GIS.PUBLIC.CODE_POINT_OPEN_WHITE_HORSE
LIMIT 10;
SELECT *
FROM GIS.PUBLIC.OPEN_UPRN_WHITE_HORSE
LIMIT 10;


SELECT *
FROM GIS.PUBLIC.CODE_POINT_OPEN_WHITE_HORSE
WHERE ST_GEOMETRYFROMEWKB("geom", 27700) IS NULL;

SELECT ST_GEOMETRYFROMEWKB("geom") 
FROM GIS.PUBLIC.OPEN_UPRN_WHITE_HORSE

limit 10;